home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('design/', views.design, name='design'),
    path('welcome/', views.welcome, name='welcome'),
    path('products/', views.ProductListView.as_view(), name='products-list'),
    path('products/<int:product_id>/', views.product_detail, name='product-detail'),
    re_path(r'^products/(?P<product_id>\d+)/variants/$', views.url_redirect),
    path('products/<int:product_id>/variants/<int:variant_id>/inventory_history/',
         views.inventory_adjustment_history_list,
         name='inventory-adjustment-history-list'),
    re_path(r'^products/(?P<product_id>\d+)/variants/(?P<variant_id>\d+)',
            views.url_redirect)
]

shopify_app/urls.py
from django.urls import path
from . import views

app_name = 'shopify_app'
urlpatterns = [
    path('', views.login, name='login'),
    path('authenticate/', views.authenticate, name='authenticate'),
    path('finalize/', views.finalize, name='finalize'),
    path('logout/', views.logout, name='logout'),
    path('webhook/inv_levels_update/', views.webhook_inventory_levels_update, name='inventory_levels_update'),
    path('webhook/inv_items_update/', views.webhook_inventory_items_update, name='inventory_items_update'),
    path('webhook/products_update/', views.webhook_products_update, name='products_update'),
    path('webhook/inv_items_delete/', views.webhook_inventory_items_delete, name='inventory_items_delete'),
    path('webhook/products_delete/', views.webhook_products_delete, name='products_delete'),
]

shopify_inv_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopify/', include('shopify_app.urls')),
    path('', include('home.urls')),
]

shopify_inv_tracker/templates/422.html
<!DOCTYPE html>
<html>
<head>
  <title>The change you wanted was rejected (422)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  <!-- This file lives in public/422.html -->
  <div class="dialog">
    <h1>The change you wanted was rejected.</h1>
    <p>Maybe you tried to change something you didn't have access to.</p>
  </div>
</body>
</html>

shopify_inv_tracker/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <title>{% block title %}Shopify Application{% endblock %}</title>
  <link href="{% static 'stylesheets/application.css' %}" media="screen" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="https://cdn.shopify.com/s/assets/external/app.js"></script>

  <script src="https://unpkg.com/@shopify/app-bridge"></script>
  <script>
    var AppBridge = window['app-bridge'];
    var createApp = AppBridge.default;
    var app = createApp({
      apiKey: '{{ api_key }}',
      shopOrigin: '{{ current_shop.myshopify_domain }}',
      forceRedirect: false
    });
    var actions = AppBridge.actions;
    var TitleBar = actions.TitleBar;
    var Button = actions.Button;
    var Redirect = actions.Redirect;

    var breadcrumb = Button.create(app, {label: 'Testing'});
    breadcrumb.subscribe(Button.Action.CLICK, function() {
      app.dispatch(Redirect.toApp({path: '/design'}));
    });

    var titleBarOptions = {
      title: '{{ page_name }}',
      breadcrumbs: breadcrumb,
    };

    var myTitleBar = TitleBar.create(app, titleBarOptions);
  </script>
</head>

<body>
  <div id="header">
    <h1><a href="{% url 'home:index' %}">Shopify Demo Application</a></h1>

    <p id="login-link">
      {% if current_shop %}
          <span class="note">Store:</span> <a href="https://{{ current_shop.myshopify_domain }}" class="shop_name" target="_blank">{{ current_shop.name }}</a> <span class="note">|</span>
          <a href="{% url 'shopify_app:logout' %}">logout</a>
      {% endif %}
    </p>
  </div>

  <div id="container" class="clearfix">
    <ul id="tabs">
      <li><a href="{% url 'home:index' %}">Home</a></li>
      <li><a href="{% url 'home:design' %}">Design Help</a></li>
    </ul>

    <!-- Flash error & notice-->
    {% if messages %}
      {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }}-message"{% endif %}>{{ message }}</div>
      {% endfor %}
    {% endif %}

    <!-- begin div.main-->
    <div id="main">
      {% block content %}{% endblock %}
    </div>
    <!-- end div.main -->
  </div>
</body>
</html>