home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('design/', views.design, name='design'),
    path('welcome/', views.welcome, name='welcome'),
    path('products/', views.ProductListView.as_view(), name='products-list'),
    path('products/<int:product_id>/', views.product_detail, name='product-detail'),
    re_path(r'^products/(?P<product_id>\d+)/variants/$', views.url_redirect),
    path('products/<int:product_id>/variants/<int:variant_id>/inventory_history/',
         views.inventory_adjustment_history_list,
         name='inventory-adjustment-history-list'),
    re_path(r'^products/(?P<product_id>\d+)/variants/(?P<variant_id>\d+)',
            views.url_redirect)
]

shopify_app/urls.py
from django.urls import path
from . import views

app_name = 'shopify_app'
urlpatterns = [
    path('', views.login, name='login'),
    path('authenticate/', views.authenticate, name='authenticate'),
    path('finalize/', views.finalize, name='finalize'),
    path('logout/', views.logout, name='logout'),
    path('webhook/inv_levels_update/', views.webhook_inventory_levels_update, name='inventory_levels_update'),
    path('webhook/inv_items_update/', views.webhook_inventory_items_update, name='inventory_items_update'),
    path('webhook/products_update/', views.webhook_products_update, name='products_update'),
    path('webhook/inv_items_delete/', views.webhook_inventory_items_delete, name='inventory_items_delete'),
    path('webhook/products_delete/', views.webhook_products_delete, name='products_delete'),
]

shopify_inv_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopify/', include('shopify_app.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models


class TestModel(models.Model):
    test_name = models.CharField(max_length=100)
    test_data = models.CharField(max_length=200)

    def __str__(self):
        return self.test_name


class FirstRun(models.Model):
    myshopify_domain = models.CharField(max_length=100, help_text='Shopify store domain.', unique=True)
    status = models.BooleanField(default=True, help_text='True if its the first visit, else False')

    def __str__(self):
        return self.status

home/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
import shopify
from shopify_app.decorators import shopify_login_required
from django.utils.decorators import method_decorator
from .helpers import first_run
from shopify_app.models import ShopifyStore, Product, Variant, InventoryAdjustmentHistory
from shopify_app.tasks import task_first_run

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from .tables import ProductTable, ProductDetailTable, InventoryAdjustmentHistoryTable
from .filters import ProductFilter


@method_decorator(shopify_login_required, name='dispatch')
class ProductListView(SingleTableMixin, FilterView):
    table_class = ProductTable
    table_pagination = {'per_page': 20}

    template_name = 'home/product.html'
    filterset_class = ProductFilter
    extra_context = {'products_list': reverse_lazy('home:products-list')}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._store = None

    def get_filterset_kwargs(self, filterset_class):
        shop_url = self.request.session['shopify']['shop_url']
        self._store = ShopifyStore.objects.get(myshopify_domain=shop_url)
        kwargs = super(ProductListView, self).get_filterset_kwargs(filterset_class)
        kwargs['store'] = self._store
        return kwargs

    def get_queryset(self):
        self.queryset = Product.objects.filter(store_id=self._store)
        return self.queryset


@shopify_login_required
def product_detail(request, product_id=None):
    try:
        store = ShopifyStore.objects.get(myshopify_domain=request.session.get('shopify').get('shop_url'))
        table = ProductDetailTable(Variant.objects.filter(store=store, product_id=product_id))
        return render(request, "home/product_detail.html", {"table": table})
    except Exception as e:
        print(e)
        return redirect(reverse('home:products-list'))


@shopify_login_required
def inventory_adjustment_history_list(request, product_id=None, variant_id=None):
    try:
        store = ShopifyStore.objects.get(myshopify_domain=request.session.get('shopify').get('shop_url'))
        variant = Variant.objects.get(store=store, product_id=product_id, variant_id=variant_id)
        table = InventoryAdjustmentHistoryTable(InventoryAdjustmentHistory.objects.filter(variant=variant))
        return render(request, 'home/inventory_history.html', {'table': table})
    except Exception as e:
        print(e)
        return redirect(reverse('home:products-list'))


def url_redirect(request, product_id=None, variant_id=None):
    if variant_id is None:
        url_params = {"product_id": product_id}
        url = reverse("home:product-detail", kwargs=url_params)
    else:
        url_params = {"product_id": product_id, "variant_id": variant_id}
        url = reverse("home:inventory-adjustment-history-list", kwargs=url_params)
    return redirect(url)


# @xframe_options_exempt
def welcome(request):
    return render(request, 'home/welcome.html', {
        'callback_url': "http://%s/login/finalize" % (request.get_host()), 'page_name': 'Welcome'
    })


@shopify_login_required
# @xframe_options_exempt
def index(request):
    store_url = request.session['shopify']['shop_url']
    products = shopify.Product.find(limit=3)
    orders = shopify.Order.find(limit=3, order="created_at DESC")
    user = ShopifyStore.objects.get(myshopify_domain=store_url)

    # if first_run(store_url):
    #     task_first_run(store_url, verbose_name=f'First run task: {user.myshopify_domain}', creator=user)
    #     test_bg_task(store_url, verbose_name=f'Test task: {user.myshopify_domain}', creator=user)

    return render(request, 'home/index.html', {
        'products': products,
        'orders': orders,
        'page_name': 'Home'
    })


# @xframe_options_exempt
def design(request):
    return render(request, 'home/design.html', {'page_name': 'Design'})

home/templates/home/design.html
{% extends "base.html" %}
{% block content %}
<h1 class="blue">Overview of the styles used</h1>

<div class="info">
  <img src="/static/images/info.gif" style="float:left">
  <p>You are free to use this demo application as a base to create new applications that use the Shopify API.</p>
</div>

<table id="style-table">
  <tr>
    <td style="width: 33%">
      <pre><code>&lt;h1&gt;Lorem ipsum&lt;/h1&gt;</code></pre>
    </td>

    <td style="width: 66%">
      <h1>Lorem ipsum</h1>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;h2&gt;Lorem ipsum&lt;/h2&gt;</code></pre>
    </td>

    <td>
      <h2>Lorem ipsum</h2>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;h3&gt;Lorem ipsum&lt;/h3&gt;</code></pre>
    </td>

    <td>
      <h3>Lorem ipsum</h3>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;h4&gt;Lorem ipsum&lt;/h4&gt;</code></pre>
    </td>

    <td>
      <h4>Lorem ipsum</h4>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;p&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;p class="note"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="note">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;span class="highlight"&gt;&hellip;&lt;/span&gt;</code></pre>
    </td>

    <td>
      <span class="highlight">Lorem ipsum dolor sit amet</p>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;h3 class="blue"&gt;&hellip;&lt;/h3&gt;</code></pre>
    </td>

    <td>
      <h3 class="blue">Lorem ipsum</h3>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;h3 class="green"&gt;&hellip;&lt;/h3&gt;</code></pre>
    </td>

    <td>
      <h3 class="green">Lorem ipsum</h3>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;h3 class="orange"&gt;&hellip;&lt;/h3&gt;</code></pre>
    </td>

    <td>
      <h3 class="orange">Lorem ipsum</h3>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;p class="blue"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="blue">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;p class="green"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="green">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>
  <tr>
    <td>
      <pre><code>&lt;p class="orange"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="orange">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;div class="box"&gt;<br />&nbsp;&nbsp;&lt;div class="wrapper"&gt;&hellip;&lt;/div&gt;<br />&lt;/div&gt;</code></pre>
    </td>

    <td>
      <div class="box"><div class="wrapper">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div></div>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;p class="dark"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="dark">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>

  <tr>
    <td>
      <pre><code>&lt;p class="light"&gt;&hellip;&lt;/p&gt;</code></pre>
    </td>

    <td>
      <p class="light">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </td>
  </tr>



</table>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% block content %}
<div id="sidebar">
  <h3>Where to start</h3>
  <h4>Check out <code style="font-size: 140%">home/views.py</code></h4>

  <p class="description">
    The index view in this demo application fetches the latest 3 orders and products and makes them available as context variables <code style="color: #218BCE">orders</code> and <code style="color: #218BCE">products</code>.
  </p>

  <h4>Check out the <code>home/index.html</code> template</h4>

  <p class="description">
    This is the Django template you are currently looking at. It is located at:<br />
  </p>

  <p style="background: #fff; margin-left: 4px"><code>home/templates/home/index.html</code></p>

  <p class="description">
    Have a look at the markup and Django template code to see how the Shopify API is being used.
  </p>

  <h3>Additional documentation</h3>

  <p class="description">
    Become an expert:
  </p>

  <ul>
    <li>
      <a href="http://www.shopify.com/developers/api/">API documentation</a>
      <span class="note">The reference: what you can do with the Shopify API.</span>
    </li>
    <li>
      <a href="http://wiki.shopify.com/">Wiki</a>
      <span class="note">Get more information and share your knowledge.</span>
    </li>
    <li>
      <a href="http://forums.shopify.com/community">Forum</a>
      <span class="note">Ask questions and see what others already wanted to know.</span>
    </li>
  </ul>

  <h3>Once you're ready</h3>

  <p class="description">
    We'd love to see what you create using the Shopify API.
    Find out how to share your application with the world and read the latest information on the <a href="http://www.shopify.com/developers/publishing/">API Publishing Page</a>.
  </p>
</div>


<div id="orders">
  <h2>Your recent orders</h2>
  {% if orders %}
    <ul>
    {% for order in orders %}
      <li>
        <div class="order box">
          <div class="wrapper">
            <strong><a href="https://{{ current_shop.myshopify_domain }}/admin/orders/{{ order.id }}" target="_blank">{{ order.name }}</a></strong>
            <span class="price">{{ order.total_price }} {{ order.currency }}</span>
            <span class="highlight">{{ order.financial_status }}</span>
            by <span class="note">{{ order.billing_address.name }}</span>
          </div>
        </div>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <em class="note">There are no orders in your store.</em>
  {% endif %}
</div>


<h2>Some of your products</h2>

{% for product in products %}
  <div class="product box">
    <div class="wrapper">
      {% if product.image %}
        <img src="{{ product.image.small }}" alt="Product Image" />
      {% endif %}

      <h4><a href="https://{{ current_shop.myshopify_domain }}/admin/products/{{ product.id }}" target="_blank">{{ product.title }}</a></h4>

      <p class="price">{{ product.price_range }} {{ current_shop.currency }}</p>
      <p style="margin-bottom: 0">{{ product.product_type }} <span class="note">type</span></p>
      <p style="margin: 0">{{ product.vendor }} <span class="note">vendor</span></p>

      <div style="clear:left"></div>
    </div>
  </div>
{% empty %}
  <em class="note">There are no products in your store.</em>
{% endfor %}

{% endblock %}

home/templates/home/inventory_history.html
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% bootstrap_css %}

<p>Inventory History</p>

{% if table.data %}
{% render_table table 'django_tables2/bootstrap.html' %}
{% else %}
No adjustments found
{% endif %}

home/templates/home/product.html
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% bootstrap_css %}

{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'Filter' %}
        {% bootstrap_button 'Reset' href=products_list %}
    </form>
{% endif %}
{% render_table table 'django_tables2/bootstrap4.html' %}

home/templates/home/product_detail.html
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% bootstrap_css %}

{% render_table table 'django_tables2/bootstrap.html' %}

home/templates/home/product_image.html
<a href="{% url 'home:product-detail' record.product_id %}"><img src="{% firstof record.image  no_image %}"></a>

home/templates/home/welcome.html
{% extends "base.html" %}
{% block content %}
<h1 class="green">Welcome</h1>

<p>
  This is an example Shopify application that shows what you can do with the Shopify API.
</p>

<h3>1. Make sure you've entered a valid <em>API-Key</em> and <em>Secret</em></h3>

<p>
  If you haven't registered your application yet, then you must do so to obtain an API-Key and Secret.
</p>

<ul>
  <li>Shop owners can create applications for themeselves through their own admin (under Apps &gt; ManageApps)</li>
  <li>Shopify Partners create applications through their <a href="https://www.shopify.com/services/partners/api_clients">admin</a></li>
</ul>

<p>
  After registering your application with Shopify, you need to edit the <code>shopify_settings.py</code> file,
  and insert your <em>API-Key</em> and <em>Secret</em> there. Then restart this application.
</p>

<h3 id="callback-step">2. Make sure your <em>callback URL</em> is correct</h3>

<p class="description">
  The URL should be <code>{{ callback_url }}</code>,
  with the host portion of the URL pointing to whichever domain is currently hosting this application. <br/>
  The callback URL of your app can be changed in the API screen of your Shopify admin interface.
</p>

<h3>3. <a href="{% url 'shopify_app:login' %}">Login</a> to your shop</h3>

<p class="description">
  On login, the shop owner will be redirected to a Shopify URL containing the <strong>API-Key</strong> of the application.
  The shop will need to grant access to your application to give it access to its private admin data.

  After authenticating, the browser will be redirected to the <code>shopify_app.views.finalize</code> view,
  which creates a session using the <strong>API-Secret</strong>, and then redirects to the example dashboard.<br/>
  The example view at <code>home.views.index</code> will get the shop's recent <code>Orders</code> and <code>Articles</code> through the
  Shopify <a href="http://www.xfront.com/REST-Web-Services.html" title="Get more information about REST web services in general">REST</a> API and list them with all of your <code>Products</code>.
  You can click on a link of one of your objects and will then be taken to the corresponding admin area of your shop.<br/>

  <p><strong>Note:</strong> There are no examples for <em>creating or editing</em> objects, but you are also able to do that with the Shopify API!</p>
</p>

<h3>4. Check out the source code of the <code>home.views.index</code> and its <code>home/index.html</code> template</h3>

<p class="description">
  You can analyze those files to see how the ShopifyAPI is used and get a glimpse of what's possible.
</p>

<h3>5. Read additional documentation</h3>

<p class="description">
  Become an expert.
</p>

<ul>
  <li>
    <a href="http://www.shopify.com/developers/api">API documentation</a>
    <span class="hint">(An overview of what you can do with the Shopify API.)
  </li>
  <li>
    <a href="http://wiki.shopify.com/">Wiki (needs its own API section)</a>
    <span class="hint">(Get more information and share your knowledge.)
  </li>
  <li>
    <a href="http://forums.shopify.com/community">Forum (needs its own API section)</a>
    <span class="hint">(Ask questions and see what others already wanted to know.)
  </li>
</ul>

<h3>6. Publish your application</h3>

<p class="description">
  This feature is not implemented yet, but it in the future it will allow you to register your application,
  so that will be shown in a public directory with a description, so that more users will take notice of it.
</p>
{% endblock %}